stages:
  - build
  - deploy

build:
  image: node:latest
  stage: build
  variables: 
    PUBLIC_URL: https://leeja744.cspages.otago.ac.nz/assignment-1/
  script:
    - yarn install
    - yarn build
  artifacts:
    paths:
      - build/

pages:
  image: alpine:latest
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - mv build public
  artifacts:
    paths:
      - public